spring:
  application:
    name: eureka-server
    profiles:
      active: localhost

server:
  port: 8761
---
spring:
  config:
    activate:
      on-profiles: localhost

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      label: main

eureka:
  instance:
    appname: eureka-server
    hostname: localhost
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka

    healthcheck:
      enabled: true
    leaseRenewalIntervalInSeconds: 30
    durationInSecs: 90

logging:
  level:
    root: debug

---
spring:
  config:
    activate:
      on-profiles: stage
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      label: main

eureka:
  instance:
    appname: eureka-server
    hostname: eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka

logging:
  level:
    root: debug
